### ISSUE TITLE
Feat : create candidate delete feature and add post,put,delete in msw

### ISSUE THREAD

**Issue by SKY-PEY** [Strong-Potato/TripVote-FE#95]
## Description
후보 삭제 기능 추가

투표 제목 수정, 투표 삭제, 후보 삭제 등 msw 추가

### Task

- [x] 후보 삭제 기능 추가
- [ ] 투표 제목 수정, 투표 삭제, 후보 삭제 등 msw 추가

**Comment by HOOOO98** [comment]
와...이슈 타이틀이 살벌한데요?
